Re-generate pipeline with latest template

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -6,99 +6,99 @@
 # Script for generating Github release / tag assets
 # and managing release notes for a software pipeline
 #
-# author:  James Hunt <james@niftylogic.com>
-# created: 2016-03-30
-#
+# original author: James Hunt <james@niftylogic.com>
+# created:         2016-03-30
+# maintainer:      Benjamin Gandon (Gstack)
 
 set -eu
 
-: ${BINARY:?required}
-: ${REPO_ROOT:?required}
-: ${RELEASE_NAME:?required}
-: ${RELEASE_ROOT:?required}
-: ${REPO_OUT:?required}
+: ${BINARY:?"required"}
+: ${REPO_ROOT:?"required"}
+: ${RELEASE_NAME:?"required"}
+: ${RELEASE_ROOT:?"required"}
+: ${REPO_OUT:?"required"}
 RELEASE_BRANCH=${RELEASE_BRANCH:-"master"}
-: ${GITHUB_OWNER:?required}
-: ${GITHUB_REPO:?required}
-: ${GIT_EMAIL:?required}
-: ${GIT_NAME:?required}
+: ${GITHUB_OWNER:?"required"}
+: ${GITHUB_REPO:?"required"}
+: ${GIT_EMAIL:?"required"}
+: ${GIT_NAME:?"required"}
+TARGETS=${TARGETS:-"linux/amd64 darwin/amd64"}
 
-if [[ -z ${VERSION_FROM} ]]; then
-  echo >&2 "VERSION_FROM environment variable not set, or empty.  Did you misconfigure Concourse?"
-  exit 2
+if [[ -z "${VERSION_FROM}" ]]; then
+    echo >&2 "VERSION_FROM environment variable not set, or empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 if [[ ! -f ${VERSION_FROM} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
-  exit 2
+    echo >&2 "Version file (${VERSION_FROM}) not found. Did you misconfigure Concourse?"
+    exit 2
 fi
-VERSION=$(cat ${VERSION_FROM})
-if [[ -z ${VERSION} ]]; then
-  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
-  exit 2
+version=$(cat ${VERSION_FROM})
+if [[ -z "${version}" ]]; then
+    echo >&2 "Version file (${VERSION_FROM}) was empty. Did you misconfigure Concourse?"
+    exit 2
 fi
 
 if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
+    echo >&2 "ci/release_notes.md not found. Did you forget to write them?"
+    exit 1
 fi
 
 ###############################################################
 
 go version; echo; echo
-#?#ORIGIN=$(pwd)
-TARGETS=${TARGETS:-linux/amd64 darwin/amd64}
-ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
 
-newgopath=${ROOT%%/gopath/*}/gopath
+newgopath=${REPO_ROOT%%/gopath/*}/gopath
 if [[ -d ${newgopath} ]]; then
-	if [[ -z ${GOPATH} ]]; then
-		GOPATH="${newgopath}"
-	else
-		GOPATH="${newgopath}:${GOPATH}"
-	fi
-	PATH="${PATH}:${newgopath}/bin"
+    if [[ -z ${GOPATH} ]]; then
+        GOPATH="${newgopath}"
+    else
+        GOPATH="${newgopath}:${GOPATH}"
+    fi
+    PATH="${PATH}:${newgopath}/bin"
 fi
 echo ">> Using GOPATH ${GOPATH}"
 go install github.com/mitchellh/gox@latest
 
 if [[ -n ${STATIC_BINARY} && ${STATIC_BINARY} != "false" ]]; then
-	export CGO_ENABLED=0
+    export CGO_ENABLED=0
 fi
 
-pushd $REPO_ROOT
+pushd ${REPO_ROOT}
 mkdir artifacts
-gox -osarch="${TARGETS}" --output="artifacts/${BINARY}-{{.OS}}-{{.Arch}}" -ldflags="-X main.Version=${VERSION}" ./...
-go build -o "${BINARY}" -ldflags="-X main.Version=${VERSION}" ${CMD_PKG:-.}
+gox -osarch="${TARGETS}" --output="artifacts/${BINARY}-{{.OS}}-{{.Arch}}" -ldflags="-X main.Version=${version}" ./...
+go build -o "${BINARY}" -ldflags="-X main.Version=${version}" ${CMD_PKG:-.}
 ./${BINARY} -v
 popd
 
-echo "v${VERSION}"                         > ${RELEASE_ROOT}/tag
-echo "${RELEASE_NAME} v${VERSION}"         > ${RELEASE_ROOT}/name
+echo "v${version}"                         > ${RELEASE_ROOT}/tag
+echo "${RELEASE_NAME} v${version}"         > ${RELEASE_ROOT}/name
 mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
 mv ${REPO_ROOT}/artifacts                    ${RELEASE_ROOT}/artifacts
 
 cat > ${RELEASE_ROOT}/notification <<EOF
-<!here> New ${RELEASE_NAME} v${VERSION} released!
+<!here> New ${RELEASE_NAME} v${version} released!
 EOF
 
 
 # GIT!
 if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "${GIT_EMAIL}"
+    git config --global user.email "${GIT_EMAIL}"
 fi
 if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "${GIT_NAME}"
+    git config --global user.name "${GIT_NAME}"
 fi
 
-(cd ${REPO_ROOT}
- git merge --no-edit "${RELEASE_BRANCH}"
- git add -A
- git status
- git commit -m "release v${VERSION}")
+(
+    cd ${REPO_ROOT}
+    git merge --no-edit "${RELEASE_BRANCH}"
+    git add -A
+    git status
+    git commit -m "release v${version}"
+)
 
 # so that future steps in the pipeline can push our changes
 cp -a ${REPO_ROOT} ${REPO_OUT}/git
 
 cat > ${NOTIFICATION_OUT:-notifications}/message <<EOS
-New ${RELEASE_NAME} v${VERSION} released. <https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/tag/v${VERSION}|Release notes>.
+New ${RELEASE_NAME} v${version} released. <https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}/releases/tag/v${version}|Release notes>.
 EOS
